const state = { user: null, tab: 'orders', orders: [], inventory: [], report: null, sound: false, seenNew: new Set() };
const app = document.querySelector('#app');
const api = async (path, options = {}) => {
  const response = await fetch(`/api/kitchen-portal${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Request failed');
  return response.json();
};
const fmt = n => `₦${Number(n || 0).toLocaleString('en-NG')}`;
const esc = value => String(value ?? '').replace(/[&<>"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[char]));
const elapsed = date => { const mins = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 60000)); return mins < 1 ? 'Just now' : `${mins} min ago`; };

function login() { app.innerHTML = `<section class="login"><div class="login-card"><div class="mark">🍲</div><div class="eyebrow">ÀMÀLÀ OLÚYÒLÉ</div><h1>Kitchen Portal</h1><p>Oluyole Town Planning kitchen operations. Sign in with your approved work account to receive and prepare live orders.</p><button class="primary" id="login">Kitchen Staff Sign In</button></div></section>`; document.querySelector('#login').onclick = () => { window.location.href = `/api/kitchen-portal/login?returnTo=${encodeURIComponent(window.location.href)}`; }; }
function shell() { app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand">Àmàlà Olúyòlé<small>OLUYOLE KITCHEN</small></div><nav class="nav"><button data-tab="orders">Orders</button><button data-tab="inventory">Inventory</button><button data-tab="report">Monthly report</button></nav><button class="signout" id="signout">Sign out</button></aside><section class="content"><header class="top"><div><h1 id="title">Kitchen Orders</h1><p id="subtitle">Live paid orders for Oluyole Town Planning</p></div><div class="user" id="user"></div></header><div id="notice" class="notice hidden"></div><main id="view"></main></section></div>`; document.querySelectorAll('[data-tab]').forEach(button => button.onclick = () => { state.tab = button.dataset.tab; render(); }); document.querySelector('#signout').onclick = async () => { await fetch('/api/auth/logout',{method:'POST',credentials:'include'}); location.reload(); }; }
function notify(message) { const node = document.querySelector('#notice'); node.textContent = message; node.classList.remove('hidden'); setTimeout(() => node.classList.add('hidden'), 4200); }
function enableSound() { const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return notify('Browser sound is not supported. Keep the order board visible.'); const context = new AudioContext(); context.resume(); state.sound = true; notify('Kitchen sound alerts are enabled.'); state.audio = context; }
function chime() { if (!state.sound || !state.audio) return; const o = state.audio.createOscillator(), g = state.audio.createGain(); o.frequency.value = 880; g.gain.setValueAtTime(.12,state.audio.currentTime); g.gain.exponentialRampToValueAtTime(.001,state.audio.currentTime+.42); o.connect(g);g.connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+.42); }
function orderCard(order) { const next = { payment_confirmed:['Accept order','accepted'], accepted:['Start preparing','preparing'], preparing:['Mark ready','ready'] }[order.status]; return `<article class="card"><div class="card-head"><div><div class="order-id">#${esc(order.orderNumber)}</div><span class="order-type">${esc(order.orderType.replace('_',' '))}</span></div><span class="time">${elapsed(order.createdAt)}</span></div><div class="items">${(order.items || []).map(item => `<div class="line-item"><span><b>${esc(item.quantity)}×</b> ${esc(item.mealName)}</span></div>${item.specialInstructions ? `<div class="note">${esc(item.specialInstructions)}</div>` : ''}`).join('') || '<div class="muted">No items recorded</div>'}</div>${next ? `<button class="action" data-order="${order.id}" data-status="${next[1]}">${next[0]}</button>` : ''}</article>`; }
function ordersView() { const groups = [['New orders',['payment_confirmed']],['In progress',['accepted','preparing']],['Ready',['ready']]]; return `<div class="toolbar"><span class="muted">Orders refresh every 10 seconds.</span><button class="movement" id="sound">${state.sound ? 'Sound on' : 'Enable sound'}</button></div><section class="board">${groups.map(([name,statuses]) => `<div class="column"><h2>${name} (${state.orders.filter(o=>statuses.includes(o.status)).length})</h2>${state.orders.filter(o=>statuses.includes(o.status)).map(orderCard).join('') || '<div class="empty">No orders here.</div>'}</div>`).join('')}</section>`; }
function inventoryView() { return `<div class="table">${state.inventory.map(item => `<div class="stock-row"><div><b>${esc(item.name)}</b><div class="muted">${esc(item.category)} · ${esc(item.unit)}</div></div><div class="${Number(item.currentStock)<=Number(item.minimumStock)?'low':''}">${esc(item.currentStock)} ${esc(item.unit)}<div class="muted">minimum ${esc(item.minimumStock)}</div></div><button class="movement" data-stock="${item.id}">Record</button></div>`).join('') || '<div class="empty">No inventory items yet.</div>'}</div>`; }
function reportView() { const d = state.report || {}; const s = d.summary || {}; return `<section class="grid"><div class="metric"><b>${esc(s.totalOrders||0)}</b><span>Orders this month</span></div><div class="metric"><b>${fmt(s.totalRevenue)}</b><span>Revenue</span></div><div class="metric"><b>${esc(s.completedOrders||0)}</b><span>Completed</span></div><div class="metric"><b>${esc((d.lowStockItems||[]).length)}</b><span>Low-stock items</span></div></section><section class="report-list"><div class="panel"><h2>Most ordered meals</h2>${(d.topMeals||[]).map(m=>`<div class="stock-row"><b>${esc(m.mealName)}</b><span>${esc(m.totalQuantity)} portions</span></div>`).join('')||'<div class="empty">No monthly data yet.</div>'}</div><div class="panel"><h2>Low-stock watch</h2>${(d.lowStockItems||[]).map(i=>`<div class="stock-row"><b>${esc(i.name)}</b><span class="low">${esc(i.currentStock)} ${esc(i.unit)}</span></div>`).join('')||'<div class="empty">All stock is above its warning level.</div>'}</div></section>`; }
async function load() { try { const [orders,inventory,report] = await Promise.all([api('/orders'),api('/inventory'),api('/report')]); const fresh = orders.filter(o=>o.status==='payment_confirmed'&&!state.seenNew.has(o.id)); if (state.seenNew.size && fresh.length) { notify(`${fresh.length} new order${fresh.length>1?'s':''} received.`); chime(); } orders.forEach(o=>state.seenNew.add(o.id)); state.orders=orders;state.inventory=inventory;state.report=report;render(); } catch (error) { notify(error.message); } }
function render() { if (!state.user) return; document.querySelector('#user').textContent = `${state.user.name || state.user.email}\n${state.user.role}`; document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab)); const titles={orders:['Kitchen Orders','Live paid orders for Oluyole Town Planning'],inventory:['Kitchen Inventory','Record stock accurately and respond to low-stock warnings'],report:['Monthly Kitchen Report','Production, top meals, and stock review']}; document.querySelector('#title').textContent=titles[state.tab][0];document.querySelector('#subtitle').textContent=titles[state.tab][1]; const view=document.querySelector('#view');view.innerHTML=state.tab==='orders'?ordersView():state.tab==='inventory'?inventoryView():reportView(); const sound=document.querySelector('#sound');if(sound)sound.onclick=enableSound; document.querySelectorAll('[data-order]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await api(`/orders/${btn.dataset.order}/status`,{method:'POST',body:JSON.stringify({status:btn.dataset.status})});await load()}catch(e){notify(e.message);btn.disabled=false}});document.querySelectorAll('[data-stock]').forEach(btn=>btn.onclick=async()=>{const amount=Number(prompt('Quantity to add (use a negative number for usage/waste):',''));if(!Number.isFinite(amount)||amount===0)return;const type=amount>0?'restock':'usage';try{await api(`/inventory/${btn.dataset.stock}/movement`,{method:'POST',body:JSON.stringify({type,quantity:amount,note:'Recorded from Kitchen Portal'})});await load()}catch(e){notify(e.message)}}); }
async function establishSessionFromHash() {
  const token = new URLSearchParams(window.location.hash.slice(1)).get('sessionToken');
  if (!token) return;
  const response = await fetch('/api/auth/session', { method: 'POST', credentials: 'include', headers: { Authorization: `Bearer ${token}` } });
  if (!response.ok) throw new Error('Could not establish the kitchen staff session.');
  window.history.replaceState({}, document.title, `${window.location.pathname}${window.location.search}`);
}
async function bootstrap() { try { await establishSessionFromHash(); const me = await api('/me');state.user=me.user;shell();await load();setInterval(()=>state.user&&load(),10000); } catch { login(); } }
bootstrap();
